### ISSUE TITLE
how is this different to an event emitter

### ISSUE THREAD

**Issue by timoxley** [pazguille/mediumjs#5]
Just curious, it looks very similar to something like [component/emitter](http://github.com/component/emitter) albeit different function names.

**Comment by pazguille** [comment]
These are so similar, but the component/emitter implementation makes use of the Observer pattern. This pattern creates observable objects which publish events of interest occur to objects which are subscribed to them.

Medium makes use of the Mediator pattern and the difference of the Mediator pattern over the Observer pattern is that a single object is responsible for communication.

http://stackoverflow.com/questions/9226479/mediator-vs-observer

**Comment by timoxley** [comment]
so I could perhaps think of it more like an 'event bus' where multiple events are driven down a single event emitter?

Considering how popular Observer pattern is perhaps add this explanation to the readme.

**Comment by pazguille** [comment]
Yes. I'm going to add this explanation to the readme. Thanks! :+1:
